export const mockDoctorData = [
  {
    id: 0,
    name: "Chan Tai Man",
    phone: "5123 4567",
    email: "taiman@gmail.com",
    address: "Room 123",
    specialty: "Cardiology",
    district: "Kowloon",
  },
  {
    id: 1,
    name: "Chan Sai Man",
    phone: "5123 4568",
    email: "saiman@gmail.com",
    address: "Room 123",
    specialty: "Cardiology",
    district: "Kowloon",
  },
  {
    id: 2,
    name: "Chan Tin Man",
    phone: "5123 4569",
    email: "tinman@gmail.com",
    address: "Room 123",
    specialty: "Cardiology",
    district: "Kowloon",
  },
  {
    id: 3,
    name: "Chan Siu Man",
    phone: "5123 4561",
    email: "siuman@gmail.com",
    address: "Room 123",
    specialty: "Cardiology",
    district: "Kowloon",
  },
  {
    id: 4,
    name: "Chan Man Man",
    phone: "5123 4562",
    email: "manman@gmail.com",
    address: "Room 123",
    specialty: "Cardiology",
    district: "Kowloon",
  },
  {
    id: 5,
    name: "Chan Tai Tai",
    phone: "5123 4567",
    email: "taitai@gmail.com",
    address: "Room 123",
    specialty: "Cardiology",
    district: "Kowloon",
  },
  {
    id: 6,
    name: "Chan Sai Sai",
    phone: "5123 4568",
    email: "saisai@gmail.com",
    address: "Room 123",
    specialty: "Cardiology",
    district: "Kowloon",
  },
  {
    id: 7,
    name: "Chan Tin Tin",
    phone: "5123 4569",
    email: "tintin@gmail.com",
    address: "Room 123",
    specialty: "Cardiology",
    district: "Kowloon",
  },
  {
    id: 8,
    name: "Chan Siu Siu",
    phone: "5123 4561",
    email: "siusiu@gmail.com",
    address: "Room 123",
    specialty: "Cardiology",
    district: "Kowloon",
  },
];
